---
collections:
        # name: sap.linux
        # version: 3.1.4
        # source: https://galaxy.ansible.com
        - name: redhat.rhel_system_roles
          version: 1.7.3
          source: https://cloud.redhat.com/api/automation-hub/
        - name: community.general
          version: 4.3.0
        - name: community.sap_install
        - name: community.sap_operations
        - name: community.sap_libs
          # requires ansible 2.9+
        - name: https://github.com/sap-linuxlab/community.sap_launchpad.git
          type: git
       
